// Code generated by MockGen. DO NOT EDIT.
// Source: handler_secret.go

// Package handlers_test is a generated GoMock package.
package handlers

import (
	context "context"
	reflect "reflect"

	secret "github.com/NailUsmanov/gophkeeper/internal/server/service/secret"
	gomock "github.com/golang/mock/gomock"
)

// MockCreateSecretService is a mock of CreateSecretService interface.
type MockCreateSecretService struct {
	ctrl     *gomock.Controller
	recorder *MockCreateSecretServiceMockRecorder
}

// MockCreateSecretServiceMockRecorder is the mock recorder for MockCreateSecretService.
type MockCreateSecretServiceMockRecorder struct {
	mock *MockCreateSecretService
}

// NewMockCreateSecretService creates a new mock instance.
func NewMockCreateSecretService(ctrl *gomock.Controller) *MockCreateSecretService {
	mock := &MockCreateSecretService{ctrl: ctrl}
	mock.recorder = &MockCreateSecretServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCreateSecretService) EXPECT() *MockCreateSecretServiceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockCreateSecretService) Create(ctx context.Context, ownerID string, req secret.CreateReq) (*secret.Secret, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, ownerID, req)
	ret0, _ := ret[0].(*secret.Secret)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockCreateSecretServiceMockRecorder) Create(ctx, ownerID, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockCreateSecretService)(nil).Create), ctx, ownerID, req)
}

// MockGetSecretService is a mock of GetSecretService interface.
type MockGetSecretService struct {
	ctrl     *gomock.Controller
	recorder *MockGetSecretServiceMockRecorder
}

// MockGetSecretServiceMockRecorder is the mock recorder for MockGetSecretService.
type MockGetSecretServiceMockRecorder struct {
	mock *MockGetSecretService
}

// NewMockGetSecretService creates a new mock instance.
func NewMockGetSecretService(ctrl *gomock.Controller) *MockGetSecretService {
	mock := &MockGetSecretService{ctrl: ctrl}
	mock.recorder = &MockGetSecretServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGetSecretService) EXPECT() *MockGetSecretServiceMockRecorder {
	return m.recorder
}

// GetByID mocks base method.
func (m *MockGetSecretService) GetByID(ctx context.Context, ownerID, secretID string) (*secret.Secret, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, ownerID, secretID)
	ret0, _ := ret[0].(*secret.Secret)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockGetSecretServiceMockRecorder) GetByID(ctx, ownerID, secretID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockGetSecretService)(nil).GetByID), ctx, ownerID, secretID)
}

// List mocks base method.
func (m *MockGetSecretService) List(ctx context.Context, ownerID string, limit, offset int, filter secret.SecretListFilter) ([]*secret.Secret, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, ownerID, limit, offset, filter)
	ret0, _ := ret[0].([]*secret.Secret)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// List indicates an expected call of List.
func (mr *MockGetSecretServiceMockRecorder) List(ctx, ownerID, limit, offset, filter interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockGetSecretService)(nil).List), ctx, ownerID, limit, offset, filter)
}

// MockUpdateService is a mock of UpdateService interface.
type MockUpdateService struct {
	ctrl     *gomock.Controller
	recorder *MockUpdateServiceMockRecorder
}

// MockUpdateServiceMockRecorder is the mock recorder for MockUpdateService.
type MockUpdateServiceMockRecorder struct {
	mock *MockUpdateService
}

// NewMockUpdateService creates a new mock instance.
func NewMockUpdateService(ctrl *gomock.Controller) *MockUpdateService {
	mock := &MockUpdateService{ctrl: ctrl}
	mock.recorder = &MockUpdateServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUpdateService) EXPECT() *MockUpdateServiceMockRecorder {
	return m.recorder
}

// Update mocks base method.
func (m *MockUpdateService) Update(ctx context.Context, ownerID, secretID string, req secret.UpdateReq) (*secret.Secret, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, ownerID, secretID, req)
	ret0, _ := ret[0].(*secret.Secret)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockUpdateServiceMockRecorder) Update(ctx, ownerID, secretID, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockUpdateService)(nil).Update), ctx, ownerID, secretID, req)
}
