// Code generated by MockGen. DO NOT EDIT.
// Source: handler_attachment.go

// Package handlers is a generated GoMock package.
package handlers

import (
	context "context"
	io "io"
	reflect "reflect"

	models "github.com/NailUsmanov/gophkeeper/internal/models"
	gomock "github.com/golang/mock/gomock"
)

// MockAttachmentService is a mock of AttachmentService interface.
type MockAttachmentService struct {
	ctrl     *gomock.Controller
	recorder *MockAttachmentServiceMockRecorder
}

// MockAttachmentServiceMockRecorder is the mock recorder for MockAttachmentService.
type MockAttachmentServiceMockRecorder struct {
	mock *MockAttachmentService
}

// NewMockAttachmentService creates a new mock instance.
func NewMockAttachmentService(ctrl *gomock.Controller) *MockAttachmentService {
	mock := &MockAttachmentService{ctrl: ctrl}
	mock.recorder = &MockAttachmentServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAttachmentService) EXPECT() *MockAttachmentServiceMockRecorder {
	return m.recorder
}

// Download mocks base method.
func (m *MockAttachmentService) Download(ctx context.Context, ownerID, attachmentID string) (*models.AttachmentMeta, io.ReadCloser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Download", ctx, ownerID, attachmentID)
	ret0, _ := ret[0].(*models.AttachmentMeta)
	ret1, _ := ret[1].(io.ReadCloser)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Download indicates an expected call of Download.
func (mr *MockAttachmentServiceMockRecorder) Download(ctx, ownerID, attachmentID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Download", reflect.TypeOf((*MockAttachmentService)(nil).Download), ctx, ownerID, attachmentID)
}

// List mocks base method.
func (m *MockAttachmentService) List(ctx context.Context, ownerID, secretID string, limit, offset int) ([]models.AttachmentMeta, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, ownerID, secretID, limit, offset)
	ret0, _ := ret[0].([]models.AttachmentMeta)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// List indicates an expected call of List.
func (mr *MockAttachmentServiceMockRecorder) List(ctx, ownerID, secretID, limit, offset interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockAttachmentService)(nil).List), ctx, ownerID, secretID, limit, offset)
}

// Upload mocks base method.
func (m *MockAttachmentService) Upload(ctx context.Context, ownerID, secretID, fileName, contentType string, r io.Reader) (*models.AttachmentMeta, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Upload", ctx, ownerID, secretID, fileName, contentType, r)
	ret0, _ := ret[0].(*models.AttachmentMeta)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Upload indicates an expected call of Upload.
func (mr *MockAttachmentServiceMockRecorder) Upload(ctx, ownerID, secretID, fileName, contentType, r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Upload", reflect.TypeOf((*MockAttachmentService)(nil).Upload), ctx, ownerID, secretID, fileName, contentType, r)
}

// Ping mocks base method.
func (m *MockAttachmentService) Ping(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Ping", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Ping indicates an expected call of Ping.
func (mr *MockAttachmentServiceMockRecorder) Ping(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Ping",
		reflect.TypeOf((*MockAttachmentService)(nil).Ping), ctx)
}
